In [1]:
import pandas as pd
import numpy as np
from unidecode import unidecode
raw = pd.read_csv('2852sc.csv', sep=";", skiprows=6, nrows=53)
raw = raw.rename(columns={'Unnamed: 0': 'Province'})
raw = raw[~raw["Province"].str.contains("Total Nacional")]
raw

ModuleNotFoundError: No module named 'pandas'

In [2]:
def get_name(name):
    cods = " ".join(name.split(" ")[1:])
    return (cods.split("/")[0]).decode('utf-8').encode('utf-8')
vget_name = np.vectorize(get_name)

raw["Province"] = vget_name(raw["Province"])
provinces = raw[["Province", "1996", "2015"]]
provinces

                  Province       1996       2015
1                 Albacete   194743.0   394580.0
2                 Alicante   904711.0  1855047.0
3                  Almería   359676.0   701211.0
4                    Araba   161354.0   323648.0
5                 Asturias   493911.0  1051229.0
6                    Ávila    80674.0   164925.0
7                  Badajoz   336566.0   686730.0
8           Balears, Illes   554925.0  1104479.0
9                Barcelona  2718621.0  5523922.0
10                 Bizkaia   554289.0  1148775.0
11                  Burgos   178919.0   364002.0
12                 Cáceres   198494.0   406267.0
13                   Cádiz   612191.0  1240284.0
14               Cantabria   281808.0   585179.0
15               Castellón   285467.0   582327.0
16             Ciudad Real   248328.0   513713.0
17                 Córdoba   386736.0   795611.0
18               Coruña, A   537311.0  1127196.0
19                  Cuenca    99821.0   203841.0
20                Gipuzkoa   351262.0   716834.0
21                  Girona   377615.0   753054.0
22                 Granada   449821.0   917297.0
23             Guadalajara   128341.0   253686.0
24                  Huelva   257613.0   520017.0
25                  Huesca   110854.0   222909.0
26                    Jaén   318430.0   654170.0
27                    León   228059.0   479395.0
28                  Lleida   219059.0   436029.0
29                    Lugo   161775.0   339386.0
30                  Madrid  3115522.0  6436996.0
31                  Málaga   800551.0  1628973.0
32                  Murcia   736238.0  1467288.0
33                 Navarra   318671.0   640476.0
34                 Ourense   149689.0   318391.0
35                Palencia    80943.0   166035.0
36             Palmas, Las   548716.0  1098406.0
37              Pontevedra   455617.0   947374.0
38               Rioja, La   155508.0   317053.0
39               Salamanca   162273.0   339395.0
40  Santa Cruz de Tenerife   496397.0  1001900.0
41                 Segovia    77443.0   157570.0
42                 Sevilla   948817.0  1941480.0
43                   Soria    44986.0    91006.0
44               Tarragona   394905.0   795101.0
45                  Teruel    68684.0   138932.0
46                  Toledo   345528.0   693371.0
47                Valencia  1246025.0  2543315.0
48              Valladolid   254146.0   526288.0
49                  Zamora    87808.0   183436.0
50                Zaragoza   466357.0   956006.0
51                   Ceuta    43034.0    84263.0
52                 Melilla    43629.0    85584.0

In [3]:
PROVINCIAS_COM = {"Ceuta": "Ceuta", "Melilla": "Melilla", "Araba": "Pais Vasco", "Albacete": "Castilla La Mancha", "Alicante":"Valencia", 
                  "Almería": "Andalucia", "Asturias": "Asturias", "Ávila": "Castilla y Leon", "Badajoz": "Extremadura",
                  "Barcelona": "Cataluña", "Burgos": "Castilla y Leon", "Cáceres": "Extremadura", "Cádiz": "Andalucia",
                  "Cantabria": "Cantabria", "Castellón": "Valencia", "Ciudad Real": "Castilla La Mancha", 
                  "Córdoba": "Andalucia", "Cuenca": "Castilla La Mancha", "Girona": "Cataluña", "Granada": "Andalucia",
                  "Guadalajara": "Castilla La Mancha", "Gipuzkoa": "Pais Vasco", "Huelva": "Andalucia", 
                  "Huesca": "Aragon", "Balears, Illes": "Islas Baleares", "Jaén": "Andalucia", "Coruña, A": "Galicia",
                  "Rioja, La": "La Rioja", "Palmas, Las": "Canarias", "León": "Castilla y Leon", "Lleida": "Cataluña",
                  "Lugo": "Galicia", "Madrid": "Madrid", "Málaga": "Andalucia", "Murcia": "Murcia", "Navarra": "Navarra",
                  "Ourense": "Galicia", "Palencia": "Castilla y Leon", "Pontevedra": "Galicia", "Salamanca": "Castilla y Leon",
                  "Santa Cruz de Tenerife": "Canarias", "Segovia": "Castilla y Leon", "Sevilla": "Andalucia", "Soria": "Castilla y Leon",
                  "Tarragona": "Cataluña", "Teruel": "Aragon", "Toledo": "Castilla La Mancha", "Valencia": "Valencia", 
                  "Valladolid": "Castilla y Leon", "Bizkaia": "Pais Vasco", "Zamora": "Castilla y Leon", "Zaragoza": "Aragon"}
def dict_to_utf(d):
    dutf = {}
    for k,v in d.iteritems():
        if isinstance(v, unicode):
            dutf[k] = v.decode('utf-8')
        else:
            dutf[k] = v
    return dutf


unidict = {k.decode('utf8'): v.decode('utf8') for k, v in PROVINCIAS_COM.items()}

def get_community(province):
    return PROVINCIAS_COM[province]

vget_community = np.vectorize(get_community)
provinces["Comunidad Autonoma"] = vget_community(provinces["Province"])
provinces

/Users/henar/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

                  Province       1996       2015  Comunidad Autonoma
1                 Albacete   194743.0   394580.0  Castilla La Mancha
2                 Alicante   904711.0  1855047.0            Valencia
3                  Almería   359676.0   701211.0           Andalucia
4                    Araba   161354.0   323648.0          Pais Vasco
5                 Asturias   493911.0  1051229.0            Asturias
6                    Ávila    80674.0   164925.0     Castilla y Leon
7                  Badajoz   336566.0   686730.0         Extremadura
8           Balears, Illes   554925.0  1104479.0      Islas Baleares
9                Barcelona  2718621.0  5523922.0            Cataluña
10                 Bizkaia   554289.0  1148775.0          Pais Vasco
11                  Burgos   178919.0   364002.0     Castilla y Leon
12                 Cáceres   198494.0   406267.0         Extremadura
13                   Cádiz   612191.0  1240284.0           Andalucia
14               Cantabria   281808.0   585179.0           Cantabria
15               Castellón   285467.0   582327.0            Valencia
16             Ciudad Real   248328.0   513713.0  Castilla La Mancha
17                 Córdoba   386736.0   795611.0           Andalucia
18               Coruña, A   537311.0  1127196.0             Galicia
19                  Cuenca    99821.0   203841.0  Castilla La Mancha
20                Gipuzkoa   351262.0   716834.0          Pais Vasco
21                  Girona   377615.0   753054.0            Cataluña
22                 Granada   449821.0   917297.0           Andalucia
23             Guadalajara   128341.0   253686.0  Castilla La Mancha
24                  Huelva   257613.0   520017.0           Andalucia
25                  Huesca   110854.0   222909.0              Aragon
26                    Jaén   318430.0   654170.0           Andalucia
27                    León   228059.0   479395.0     Castilla y Leon
28                  Lleida   219059.0   436029.0            Cataluña
29                    Lugo   161775.0   339386.0             Galicia
30                  Madrid  3115522.0  6436996.0              Madrid
31                  Málaga   800551.0  1628973.0           Andalucia
32                  Murcia   736238.0  1467288.0              Murcia
33                 Navarra   318671.0   640476.0             Navarra
34                 Ourense   149689.0   318391.0             Galicia
35                Palencia    80943.0   166035.0     Castilla y Leon
36             Palmas, Las   548716.0  1098406.0            Canarias
37              Pontevedra   455617.0   947374.0             Galicia
38               Rioja, La   155508.0   317053.0            La Rioja
39               Salamanca   162273.0   339395.0     Castilla y Leon
40  Santa Cruz de Tenerife   496397.0  1001900.0            Canarias
41                 Segovia    77443.0   157570.0     Castilla y Leon
42                 Sevilla   948817.0  1941480.0           Andalucia
43                   Soria    44986.0    91006.0     Castilla y Leon
44               Tarragona   394905.0   795101.0            Cataluña
45                  Teruel    68684.0   138932.0              Aragon
46                  Toledo   345528.0   693371.0  Castilla La Mancha
47                Valencia  1246025.0  2543315.0            Valencia
48              Valladolid   254146.0   526288.0     Castilla y Leon
49                  Zamora    87808.0   183436.0     Castilla y Leon
50                Zaragoza   466357.0   956006.0              Aragon
51                   Ceuta    43034.0    84263.0               Ceuta
52                 Melilla    43629.0    85584.0             Melilla

In [4]:
communidad_autonoma = provinces.groupby("Comunidad Autonoma").sum()
communidad_autonoma["increase"] = (communidad_autonoma["2015"] - communidad_autonoma["1996"])/communidad_autonoma["1996"]
order = communidad_autonoma.sort_values(by=["increase"], ascending=False)
order

                         1996       2015  increase
Comunidad Autonoma
Asturias             493911.0  1051229.0  1.128377
Galicia             1304392.0  2732347.0  1.094728
Cantabria            281808.0   585179.0  1.076517
Castilla y Leon     1195251.0  2472052.0  1.068228
Madrid              3115522.0  6436996.0  1.066105
Pais Vasco          1066905.0  2189257.0  1.051970
Valencia            2436203.0  4980689.0  1.044447
Extremadura          535060.0  1092997.0  1.042756
Aragon               645895.0  1317847.0  1.040342
La Rioja             155508.0   317053.0  1.038821
Andalucia           4133835.0  8399043.0  1.031780
Castilla La Mancha  1016761.0  2059191.0  1.025246
Cataluña            3710200.0  7508106.0  1.023639
Navarra              318671.0   640476.0  1.009835
Canarias            1045113.0  2100306.0  1.009645
Murcia               736238.0  1467288.0  0.992953
Islas Baleares       554925.0  1104479.0  0.990321
Melilla               43629.0    85584.0  0.961631
Ceuta                 43034.0    84263.0  0.958056